# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Audiofile < Formula
  desc ""
  homepage "https://github.com/lcastrooliveira"
  version "0.3"

  on_macos do
    url "https://github.com/lcastrooliveira/audiofile/releases/download/v0.3/audiofile_Darwin_all.tar.gz"
    sha256 "47a5e04c3a91d3fbc3f24749fa064ba445e89f7dbed1a5493d09a8352e4327ed"

    def install
      bin.install "audiofile"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lcastrooliveira/audiofile/releases/download/v0.3/audiofile_Linux_x86_64.tar.gz"
      sha256 "f51178b0ca784c90b2098e394c428ee86cf498f7792dbb1093605f414d315f0c"
      def install
        bin.install "audiofile"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lcastrooliveira/audiofile/releases/download/v0.3/audiofile_Linux_arm64.tar.gz"
      sha256 "f0a2016831d722095f6835e13810dd4534add806d47550db4a1d4470fdb09134"
      def install
        bin.install "audiofile"
      end
    end
  end
end
